---
bibliography: [refs.bib]
---

# Introduction

Universities and other higher education institutions are central to the production and dissemination of knowledge, contributing to human capital development. Instructors' decisions about how to teach, whether to collaborate with colleagues, which materials to assign, and how broadly to define course content, have a substantial influence on students' educational experience, shaping their learning outcomes and career trajectories [@bakkenes2010teacher;@vembye2024effects;@han2023interdisciplinary]. Instructors' individual preferences and institutional constraints shape these choices, which may not always align with students' best interest. For instance, instructors may prefer working alone or with colleagues from similar backgrounds, which can limit course diversity and interdisciplinarity, reinforce gender stereotypes in specific subjects [@ellemers2018gender;@lockwood2006someone;@canaan2023impact]. Collaboration among instructors can also affect their professional development by exposure to different teaching methodologies [@buckingham2021learning]. Despite their significance, research on the underlying factors that drive these teaching choices remains limited, primarily due to a lack of data.

This study addresses this gap by analysing a large dataset of English course syllabi from 1990 to 2023 across fifteen countries, which has been previously used to study school curricula [@han2023interdisciplinary], teaching metrics [@nowogrodzki2016mining], the impacts of AI [@gao2023quantifying], and the education-innovation gap [@biasi2022education]. The dataset enables a systematic, quantitative analysis of long-term trends. Each syllabus includes instructor gender, institutional affiliation, course field, assigned readings, and a course description. This allows us to examine gender-based team formation, revealing potential preferences and institutional constraints in teaching collaborations. Furthermore, we analyse how team composition, particularly gender and size, relates to teaching practices, such as interdisciplinarity and reading assignments, while controlling for institutional factors, field, academic year, and other relevant variables.

Specifically, this study addresses two key questions. First, how often do academics choose to teach alone versus co-teach with a colleague, and to what extent are co-teaching teams composed of mixed-gender pairs? Second, how do the size and gender composition of teaching teams relate to key aspects of teaching: (1) the course's interdisciplinarity, (2) the novelty of assigned readings, and (3) the gender representation of the cited authors? Previous research has shown that these aspects shape students' learning outcomes and career trajectories [@bakkenes2010teacher; @vembye2024effects; @han2023interdisciplinary] while also influencing instructors' professional development and promotion within their institutions [@buckingham2021learning].

Our results reveal a significant role for gender in co-teaching practices, with mixed-gender teams occurring consistently less frequently than same-gender teams across institutions and fields. Furthermore, mixed-gender teams arise much less often than expected under a null model that forms teams in a gender-neutral manner while keeping fixed field-related and institutional constraints. These findings underscore a persistent and widespread underrepresentation of mixed-gender collaborations in teaching, that is not fully explained by unobserved differences across fields or institutions. 

Our analysis further reveals a significant and strong association between the gender composition of a teaching team and the course's interdisciplinarity, with mixed-gender teams being more interdisciplinary than all-male teams or courses taught by individual instructors. This evidence suggests that gender diversity can be a potential lever for increasing interdisciplinary teaching in tertiary education. We also find a significant association between team configurations and the fraction of cited female authors. Specifically, classes taught by a female instructor alone tend to cite a higher fraction of female authors compared to courses taught by male instructors, with mixed-gender teams falling in between. This highlights teaching practices as an understudied potential driver of the underrepresentation of women in academia. Finally, we also observe a trend in novelty, with female instructors assigning more recent readings than their male counterparts, regardless of team size. This evidence contributes to the debate on the factors shaping the education-innovation gap [@biasi2022education].

While prior research has investigated academics decision-making, especially how they form research collaborations [@guimera2005team;@wuchty2007increasing;@milojevic2014principles;@yang2022gender], less is known about their teaching choices, including the formation of co-teaching teams, interdisciplinarity, and reading selections, and their effects on student outcomes.

Our findings contribute to the literature on gender dynamics in academia, particularly research team formation [@milojevic2014principles;@boschini2007team;@love2022impact], which has shown significant gender homophily --- a tendency to collaborate with colleagues of the same gender [@kwiek2021gender]. It also examines gender differences in citation patterns, a driving factor of the persistent gender bias in academia [@boivin2024sexism], including tenure promotion [@weisshaar2017publish], grant success [@bedi2012gender], co-authorships [@boschini2007team], and peer recognition [@sarsons2017recognition;@card2022gender]. While prior research has primarily focused on these areas, we shift our attention to the citation gap in teaching. This issue may not only reinforce existing gender bias in academia but also shape students' learning outcomes and future career choices [@card2022impact], effects that are less well understood.

## Female Instructors and Reading Representation

A growing body of research examines why women are underrepresented or undercited in academic work. Scholars tend to cite others of the same gender—a phenomenon known as gender homophily [@REFs]—and male-dominated fields may confer a “first-mover advantage” to men [@REF]. Other contributing factors include different self-citation patterns [@REFs] and overall gaps in publication output [@REF]. Evidence that these disparities extend into teaching is more limited, but studies indicate that female scholars are underrepresented in course syllabi [@harris2020diversify; @colgan2017gender; @skitka2021gender]. This underrepresentation appears linked to the instructor's gender. For example, in Political Science, instructors' gender predicts the assignment of female-authored readings, suggesting a form of gender homophily in course content [@smith2020gender]. Similarly, in research on political science xxxx, @dion2018gendered finds that female-led teams cite more women, whereas mixed-gender teams do not cite more women than all-male teams. These findings suggest that team composition and dynamics strongly influence decisions about what to cite or include in course readings. A key goal of our study is to investigate these patterns on a large scale across multiple domains and institutions.

## Mixed-Gender Teams and Reading Novelty

Another topic we aim to investigate is how gender composition and size of teaching teams is associated with the recenncy and scientific novelty of the readings. Extensive research has shown that gender-diverse teams tend to generate more novel and higher-impact ideas than single-gender teams in scientific collaboration [e.g., @yang2022gender]. Related work on research and R&D teams links gender diversity to more radical or innovative outputs, as well as to improved decision-making and performance [@Diaz2013; @apesteguia2012impact; @opstrup2015right; @bear2011role; @campbell2013gender; @love2022impact]. However, in teaching, the relationship with recency and scientific novelty is less understood. First, it is hard to define novelty in that context, as readings often refer to textbooks instead of journal articles for which we know how to measure scientific novelty. [Referee old text becomeing new insight]. However, we can expect the team composistion to associate with novelty, and we aim to investigate empirically this topic. [Combining teachers cna lead to share practiceis and increase novelty of teaching ...].  

## Mixed-Gender Teams and Interdisciplinary Integration

Research on scientific collaboration shows that teams play an increasingly important role in knowledge production and often draw on multiple fields [@wuchty2007increasing; @milojevic2014principles]. Recent evidence suggests that women, on average, undertake more interdisciplinary research than men [@pinheiro2022women], and that interdisciplinary collaborations can produce broader scientific outcomes [@specht2022interdisciplinary]. Taken together, this work suggests that the presence of women in a team is associated with more interdisciplinary intellectual contributions. In a teaching context, however, other factors may influence this relationship. For example, being interdisciplinary in resarch does not necessiarly translte into interdisciplinary teaching styles. Furtheormore, students may not demand for interdisciplinary courses. Or there might be institutional constraints where programs are not designed to support interdisciplinarity. Finally, also team dynamics or matching patterns, may prevent instructors to find good partners for interdisciplinary courses. To shed lights on these issues, we explored at a large scale the relationships between course interdisciplinarity, team size, and gender composition in teaching. [?]

# OLD NOTES
---- 


By focusing on the relationships between teaching and interdisciplinarity, our work also contributes to the literature on the factors influencing interdisciplinarity in academia. There is evidence that interdisciplinarity research is less likely to be funded [@bromham2016interdisciplinary], tends to attract fewer citations when it is highly interdisciplinary [@lariviere2010relationship], and is correlated with the probability of publication in academic journals [@xiang2025evaluating]. Furthermore, students attending colleges with more interdisciplinary courses tend to earn higher earnings after graduation [@evans2016measuring;@han2023interdisciplinary]. We extend this work by examining the association between gender composition and interdisciplinarity in teaching, showing that mixed-gender teams occur less frequently but tend to be more interdisciplinary. This finding suggests that removing barriers to mixed-gender team formation may increase interdisciplinarity in teaching.

We also build on prior research on the underrepresentation of female-authored works in university curricula, which has been shown within specific fields (psychology and international relations) and at a small scale [@skitka2021gender;@colgan2017gender;@harris2020diversify]. Our results reveal a consistent and significant gap in the number of cited works between female and male instructors, which is only partially addressed within mixed-gender co-teaching. This evidence highlights teaching practices as an important factor shaping gender differences in recognition among scholars.

Finally, studies about team formation are especially relevant to our work. These studies have found that mixed-gender teams tend to perform better in various settings [@yang2022gender;@bear2011role]. In research collaboration, for example, mixed-gender teams often obtain more citations, produce more novel research, publish in more prestigious journals, and are more interdisciplinary [@maddi2021gender; @yang2022gender]. Although we do not measure team "performance" as we lack data on students outcomes, our results show that mixed-gender co-teaching teams are consistently less likely to form, but, once created, they tend to deliver different outcomes, especially a higher interdisciplinarity, that previous literature has suggested having an impact on students outcomes as discussed above.



This paper draws on a large corpus of English-language course syllabi
from 1990 to 2019 across fifteen countries. The dataset has been used to
study curricular patterns [@nowogrodzki2016mining], the impact of
artificial intelligence on scientific production [@gao2023], the
education--innovation gap [@biasi2022education], and the structure of
interdisciplinary training [@han2023interdisciplinary]. Each syllabus
includes information on instructor gender, institutional affiliation,
academic field, course description, and assigned readings. These
features allow us to examine two related dimensions: (1) how often
academics teach alone versus co-teach with a colleague, and to what
extent co-teaching teams are mixed-gender; and (2) how the gender
composition of teaching teams relates to the interdisciplinarity of
course content, the recency of assigned materials, and the
representation of women among authors cited in course readings. Because
these outcomes reflect distinct mechanisms, we draw on different strands
of literature: research on homophily and team formation, work on
gendered citation patterns, and studies linking gender composition to
novelty and interdisciplinarity in collaborative work.

#### Team formation and gender homophily

Research examining team formation in science and professional networks has found that collaboration patterns exhibit strong gender homophily: individuals tend to associate with others who are similar to them [e.g., @mcpherson2001birds]. In research, scholars in economics, the life sciences, and other fields tend to co-author disproportionately with same-gender colleagues [@mcdowell1992effect; @boschini2007team; @holman2019researchers; @kwiek2021gender]. This form of gender-based sorting is not only driven by institutional constraints, as it appears even in large and diverse research environments [REF] and it persists across career stages [REFs], and is considered a contributing factor to gender inequalities in academia [XX]. Despite this evidence on gender homiphily in research, the collaboration patterns in teaching are less well understood. On the one hand, homophily to influence teaching collaboration as it does in research teams. On the other, teaching presents unique features, such as XXX, and XXXX that can gender homophily to a greater extent. For exmaple, institutional constraints (teaching is mostly in person) and individual preferences for complementary skills in teaching could differe [XXX]. Yet, the imapct of students of these choices can be significant, and lacking a fully understanding can contribute to xxxx. This motivates our effort to understand the prevalence of teaching teams and the gender composition of co-teaching teams across various fields and institutions.

#### Gender composition of teams and underrrepresentation of women in citations

A related phenomen is the persistent underrerpresentatino of women's work in academia. Research shows that

<!-- Research on citation behavior also shows that women are cited less
frequently than men in many fields, and that female-authored work tends
to cite women more than male-authored work does (see, e.g., for
international relations @maliniak2013; for astronomy
@caplar2017quantitative; for biomedical sciences @dworkin2020extent; for
economics and finance @wang2021gendered; for mathematics and computer
science @teich2022citation). Notably, @dion2018 find that while
female-authored articles in political science cite more women,
mixed-gender author teams do *not* cite more women than all-male teams. -->

#### Teams, Gender and interdisciplinarity

Research on scientific collaboration shows that teams play an increasingly important role in knowledge production and often draw on multiple fields [@wuchty2007increasing; @milojevic2014principles]. Recent evidence suggests that women, on average, undertake more interdisciplinary research than men [@pinheiro2022women], and that interdisciplinary collaborations can produce broader scientific outcomes [@specht2022interdisciplinary]. Taken together, this work suggests that the presence of women in a team is associated with more interdisciplinary intellectual contributions. In a teaching context, however, other factors may influence this relationship. For example, being interdisciplinary in resarch does not necessiarly translte into interdisciplinary teaching styles. Furtheormore, students may not demand for interdisciplinary courses. Or there might be institutional constraints where programs are not designed to support interdisciplinarity. Finally, also team dynamics or matching patterns, may prevent instructors to find good partners for interdisciplinary courses. To shed lights on these issues, we explored at a large scale the relationships between course interdisciplinarity, team size, and gender composition in teaching. [?]

#### Mixed-gender teams and novelty

Another topic we aim to investigate is how gender composition and size of teaching teams is associated with the recenncy and scientific novelty of the readings. Extensive research has shown that gender-diverse teams tend to generate more novel and higher-impact ideas than single-gender teams in scientific collaboration [e.g., @yang2022gender]. Related work on research and R&D teams links gender diversity to more radical or innovative outputs, as well as to improved decision-making and performance [@Diaz2013; @apesteguia2012impact; @opstrup2015right; @bear2011role; @campbell2013gender; @love2022impact]. However, in teaching, the relationship with recency and scientific novelty is less understood. First, it is hard to define novelty in that context, as readings often refer to textbooks instead of journal articles for which we know how to measure scientific novelty. [Referee old text becomeing new insight]. However, we can expect the team composistion to associate with novelty, and we aim to investigate empirically this topic. [Combining teachers cna lead to share practiceis and increase novelty of teaching ...].  

<!-- These studies focus on research teams rather than teaching, but they suggest that gender-diverse groups may explore a broader space of ideas and combinations. In our context, this motivates examining both the *recency* of assigned readings, measured as the time between a work's publication and its appearance in a syllabus, and the *novelty* of the assigned readings. -->

<!-- Despite extensive research on gender dynamics in academic collaboration
and citation practices, far less attention has been paid to how these
dynamics shape university teaching, particularly the formation of
teaching teams and the content they generate. This gap motivates our
examination of how the gender composition of instructors relates to what
appears in course syllabi. -->

Our analysis reveals several important findings.  First, we find that mixed-gender teaching teams are consistently less common than expected under a gender-neutral benchmark, even after accounting for institutional, disciplinary, and temporal factors. Mixed-gender teams are associated with more interdisciplinary course content, consistent with evidence on the collaborative benefits of gender diversity. With respect to reading assignments, female instructors assign a higher share of women-authored works, while mixed-gender teams fall between all-male and all-female instructors. Finally, courses taught by female instructors tend to include more recent readings than those taught by male instructors, with mixed-gender teams again showing intermediate patterns. Together, these findings highlight teaching practices as an important and understudied dimension of gender inequalities in academia.