---
bibliography: refs.bib
---

# Materials and Methods {#sec:methods}

## Data sources

### Open Syllabus corpus

The core dataset consists of a corpus of more than six million university syllabi compiled by Open Syllabus (New York, US) through web extractions from university websites. These extractions identified syllabi with a median confidence level of 99.8%. A tagging algorithm extracts key course details, such as the title, description, academic year, language, a list of anonymised instructors, and the assigned readings.^[Documentation available at: https://docs.opensyllabus.org] OpenSyllabus also assigns each syllabus to one of 69 top-level disciplinary fields, derived from the U.S. Department of Education's CIP classification system.^[
  The CIP classification is available at: 
  https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=55
] 

Because course level (e.g., undergraduate or graduate) was not explicitly reported in our data, we inferred it from course codes. For example, “Psychology 101” typically denotes an introductory course, whereas “Psychology 401” indicates a more advanced offering. Using this heuristic, we categorized syllabi into four levels: basic, advanced, graduate, or unknown (see Supplementary Methods).^[
  According to @biasi2022education, this classification procedure is approximately 85% accurate for a sample of U.S. courses that could be matched to catalogues with verifiable information.
]

While the original dataset includes syllabi in 49 languages, most documents (96%) are in English. For simplicity, we focused exclusively on English-language syllabi.^[
  Our focus on English-language courses means that, while we have comprehensive data for English-speaking countries such as Canada, Ireland, the United States, and Great Britain, the sample in non-English-speaking countries tends to be more representative of internationally oriented universities. These are typically institutions offering programs in English or advanced-level courses, such as postgraduate programs or disciplines where English is the primary medium of instruction within traditional universities.
] This choice resulted in a total of 5.4 million syllabi (1990-2019) from approximately 4,000 higher education institutions across fifteen countries (Table \@ref(tab:SI-country)).

## Instructor genders

Each syllabus lists one or more instructors, with 76% listing a single instructor, 16% listing two, 4% listing three, and 4% listing more than three instructors. OpenSyllabus determined the instructors gender automatically based on their names, resulting in 52% male, 37% female, and 11% unknown categories. (Table \@ref(tab:SI-composition) illustrates the gender composition of the teaching teams). After excluding syllabi with unknown gender, the distribution was 58% male and 42% female instructors, which aligns closely with the 45% of female academic staff reported in OECD countries [@oecd2022]. A detailed empirical analysis of the represenativeness of our gender popoluation is in the Supplementary Information. 


### Linking syllabi to bibliometric data

About 2.9 million syllabi (53% of the total) list readings matched with bibliographic sources, providing additional metadata on authorship, journal of publication, and publication year. Institutions are matched to a list of more than 22,000 entities from the Research Organisation Registry, providing further metadata on institutional characteristics, including country and enrollment figures. Overall, the institutions in our sample account for over 35 million enrolled students today.^[
  For more details on how OpenSyllabus classify and match the data, the related documentation is available online at https://docs.opensyllabus.org.
]

To assess the scientific novelty of the readings assigned in each syllabus, we further linked the data to SciSciNet (v2) [@lin2023sciscinet], a large-scale database of scientific publications that includes pre-computed indicators of novelty, such as the atypicality measure introduced by Uzzi et al. [@uzzi2013atypical]. Matches were performed using article DOIs, yielding approximately XXXX successfully matched publications, corresponding to XXX% of all readings with an available DOI. These matched publications appear in roughly 300,000 syllabi, representing about 10% of the 2.9 million syllabi containing reading lists. 

The same methods used to identify the gender of the instructors were used for the gender of the authors listed in the readings, resulting in 32% female and 56% male authors, with 12% of the authors having an unknown gender.


### Supplementary Covid-19 dataset

To examine changes associated with the Covid-19 lockdown period, we supplement this dataset with a second corpus consisting of 2.2 million syllabi of courses between 2019 and 2023 from 33 European countries (EU-27 plus Switzerland, Norway, Iceland, the United Kingdom, and Liechtenstein).

## Outcome variables 

Building on prior research highlighting the value of exposing student to cutting-edge knowledge [@biasi2022education], the influence of interdisciplinary training on career outcomes [@han2023interdisciplinary], and evidence of gender disparities in academic recognition [@aksnes2011female; @chatterjee2021gender; @tekles2022same], we focus on a set of outcome variables designed to capture these dimensions of the assigned readings and course content. These variables allow us to examine how team configurations, including gender composition and team size, are associated with the interdisciplinarity of assigned readings and their key characteristics, such as publication age and the inclusion of female-authored works. The outcome variables are described in detail below; a concise summary is in Table \@ref(tab:outcomes).

```{r outcomes, echo = FALSE, warning = FALSE, message = FALSE}
names <- c(
    "Interdisciplinarity", 
    "Age of Readings", 
    "Atypicality",
    "Novelty of readings",
    "Ratio of Female Authors"
)
def <- c(
    "Percentile rank of the course's interdisciplinarity score for the year.",
    "Percentile rank of the average publication age of assigned readings.",
    "Average of the atypicality measure of assigned readings",
    "Percentile rank of the average of new readings",
    "Proportion of women authors in the assigned readings."
)

kableExtra::kbl(
    data.frame(Name = names, Definition = def),
    booktabs = TRUE,
    caption = "Outcome variables",
    col.names = c("Variable", "Definition"),
    align = c("l", "l"),
    linesep = "\\addlinespace"
) |>
    kableExtra::kable_classic(full_width = TRUE, html_font = "Times") |>
    kableExtra::column_spec(1, width = "4cm", bold = TRUE) |>
    kableExtra::column_spec(2, width = "10cm") |>
    kableExtra::row_spec(0, bold = TRUE, align = "center") |>
    kableExtra::kable_styling(position = "center", font_size = 12)
```

### Interdisciplinarity

We measured interdisciplinarity by analysing course descriptions from syllabi, following Evans et al. [@evans2016measuring; @han2023interdisciplinary]. This approach converts course descriptions into "bags of words", where word frequencies are normalised by the inverse ratio of term frequency to document frequency (TF-IDF). We then computed a correlation matrix of word usage across academic fields to quantify the conceptual distances between them. The interdisciplinarity score for each syllabus was calculated as a weighted average of pairwise correlations with other syllabi, with weights reflecting field distance (see Supporting Information, Section \@ref(si-interdisciplinarity)). This method ensures that syllabi associated with distant fields, either academically or conceptually, are considered more interdisciplinary.^[
  To scale to millions of documents, we used random subsampling of academic fields over years and averaged results across subsamples for robustness (see Supporting Information, Section \@ref(si-interdisciplinarity)).
]

We expressed interdisciplinarity for each syllabus $i$ as the percentile rank within each academic year of the interdisciplinarity score:
$$
  \text{Interdisciplinarity}_i = \text{PR}_{yr} (\text{Interdisciplinarity Score}_i),
$$
Where $\text{PR}_{yr}$ represents the percentile rank function applied to all syllabi within a given year $yr$. This normalisation controls for skewed score distributions and allows comparison across years.

### Novelty, Recency, and Atypicality

To characterise the novelty of the assigned readings, we used three key dimensions: (1) the age of the readings and the proportion of female authors represented; (2) the frequency of new articles or books introduced in the syllabus; and (3) the median pre-computed measure of Uzzi et al's atypicality [@uzzi2013atypical]. 

First, we define the total number of references, $N_i$, as the sum of articles, books, and chapters listed in a syllabus $i$. This variable serves as a broad measure of a course's "breadth," as more assigned readings may indicate a more extensive or comprehensive curriculum. Then, we define the _Age of Readings_ variable as the difference between the syllabus year ($\text{Year}_i$) and the average publication year of the assigned readings $k=1,\cdots,K$:  
$$
  \text{Age of Readings}_i = \text{PR}_{yr}\left(\text{Year}_i - \sum_{k=1}^{N_i} \text{Publication Year}_k / N_i\right),
$$
Where $\text{PR}_{yr}$ represents the percentile rank function applied to all syllabi within a given year $yr$. This variable provides a proxy of how recent, or "novel," the readings are. While more sophisticated methods to measure novelty are available [@uzzi2013atypical; @wang2017bias], we employ this more straightforward approach because pedagogical innovation tends to be incremental, and computationally intensive methods are impractical for large-scale datasets like ours. We anticipate that novelty will vary across fields (e.g., history courses may cite older texts more frequently than computer science courses). Still, within-field differences in novelty serve as a proxy for how close a course is to the current frontier of knowledge ("novelty").

### Women Authors Cited

Finally, we define the _Ratio of Female Authors_ as the proportion of female authors among all authors in the assigned readings: 
$$
  \text{Ratio of Female Authors}_i = \frac{\text{Female Authors}_i + 1} {\text{Female Authors}_i + \text{Male Authors}_i + 2}.
$$
Here, we add two pseudo-observations (one for each gender) to stabilise the ratio, preventing extreme values in cases with very few authors [@agresti2000simple]. This metric enables us to examine whether gender and collaboration are associated with the representation of female-authored work in teaching.


## Simulating Teaching Collaborations

Building on previous research showing that gender-diverse teams are underrepresented in science [@guimera2005team], we investigate the evolution of the gender composition of co-teaching teams to determine whether it deviates from what is expected under a gender-neutral matching process. Crucially, this analysis accounts for the fact that team formation is influenced not only by individual preferences but also by institutional factors, such as departmental affiliation or academic field, as co-teaching typically occurs among faculty within the same department or the same academic field. To account for these institutional constraints, we employ a Monte Carlo randomisation approach adapted from Uzzi et al. [@guimera2005team;@uzzi2013atypical]. This approach preserves the overall gender composition and team size distribution while randomly reassigning instructors within strata defined by institution, field, and academic year. This simulation generates a randomised network in which instructors form teams independently of gender while maintaining the underlying institutional and disciplinary constraints. Therefore, by comparing actual data against teams formed in the randomised network, we can assess the difference between the observed team gender composition in the data and a counterfactual situation where instructors formed teams in a gender-neutral manner. See the details in the Supplementary Information (Section \@ref(si-simulations)).

## Regression analysis

To evaluate the association between gender composition, team size, and course content, we define four teaching team configurations, $j\in \{F, M, MM, MF/FM, FF\}$, where F and M denote female and male instructors teaching alone, respectively. MM represents two male instructors; FM/MF indicates mixed-gender pairs; and FF corresponds to two female instructors. We then employ regression analysis to study the association between these team configurations and course outcomes across academic years, $t = 1999, \cdots, 2020$. As discussed before, the outcomes of interest include (1) interdisciplinarity, (2) the average age of readings, and (3) the proportion of cited female authors. To estimate these effects, we employ the following linear mixed-effects model:
\[
Y_{j, t} = 
 \alpha_t + 
 \text{Team}_{j, t} + 
 \text{STEM}_t + \eta_{f,t} +  % fields
 \text{Country}_{t} + \text{Enroll}_t + \delta_{t} + 
 \epsilon_{j, t}.
\]
Where: 

- $Y_{j, t, f, c, s}$ is the outcome variable for team configuration $j$ in year $t$, field $f$, and school $s$,

- $\alpha_t$ is a fixed effect for the academic year $t$,

- $\text{Team}_{j, t}$ is a fixed effect for team configuration $j$ in year $t$,

- $STEM_t$ is a fixed effect for STEM courses in year $t$,

- $\eta_{f,t}$ is a random intercept for academic field $f = 1,\cdots, 69$ at year $t$,

- $\text{Country}_{c, t}$ is fixed effects for the institution $s$'s country $c$ in year $t$,

- $\text{Enroll}_{t}$ is an effect for the institution's enrollment size at year $t$,

- $\delta_{s, t}$ is a random intercept for each of approximately 4000 unique institutions,

- $\epsilon_{j,t}$ is the residual error term.

Together, the model allows us to examine the association between teaching team configurations and citation-related course outcomes while accounting for potential confounding factors across disciplines and institutions.