---
bibliography: [refs.bib]
---

# Discussion

## Summary of the findings

Our analysis of approximately five million syllabi from over 4,000 universities in fifteen countries reveals several key findings. First, while the share of classes taught by female instructors has been increasing over the last twenty years, the fraction of mixed-gender co-teaching classes has remained consistently low (3%) and significantly below that of same-gender teams (10%). This trend can stem from a lack of gender diversity in specific fields or from administrative practices that limit opportunities to form mixed-gender collaborations. However, it can also arise from gender preferences in team formation, whereby instructors tend to form teams with same-gender partners ("homophily"), a tendency already observed in research collaborations and other academic domains [e.g., @kwiek2021gender].

Our analysis shows that the underrepresentation of mixed-gender teams persists even after accounting for unobserved differences across fields, institutions, and academic years. Specifically, employing Monte Carlo simulations that randomly form teams in a gender-neutral manner, our analysis controls for typical institutional constraints, such as maintaining constant course loads across institutions and 69 academic fields within a given year. By comparing simulated to actual teams, we find that instructors tend to partner with same-gender colleagues more than twice as expected between 2005 and 2019. This result is robust across academic fields, although it is more pronounced in specific fields (Chemistry, Business, Medicine). Additionally, the underrepresentation of mixed-gender teams is consistent across countries, with the greatest effect in EU countries, where only 5% of courses are taught by mixed-gender teams, compared to an expected 12%.

Additional insights emerged from the analysis of team patterns before and after the COVID-19 pandemic (2017-2022) across thirty-three European countries. First, the pandemic caused a general decline in the number of courses, consistent across fields and countries, but this decline was disproportionately concentrated among individual instructors rather than collaborative teams. This finding likely reflects the reduction in in-person course offerings, which were primarily taught individually. Second, although collaborative teams were relatively less affected by the overall drop in courses, mixed-gender teams declined disproportionately. Taken together, these findings suggest that the formation of mixed-gender teaching teams depends more on in-person interactions than other types of teaching collaborations.

Our analysis further highlights how different team configurations are associated with key aspects of teaching: (i) mixed-gender teams tend to be more interdisciplinary than all-male teams, (ii) all-female teams tend to assign more recent readings, (iii) mixed-gender teams tend to cite more "conventional" readings (i.e., those cited in other syllabi before) and less at the frontier of scientific research (i.e., lower mean atypicality) and (iv) mixed-gender teams tend to cite a higher share of female authors than all-male teams, but less than all-female teams. These associations are not driven by unobserved differences across fields, course levels, institutions, and years that we account for in the regressions. Furthermore, these findings expand existing literature in the following ways.


## Main Contributions

First, our findings on team formation extend prior research on academic collaboration, which has traditionally focused on research partnerships [@boschini2007team;@wuchty2007increasing;@maddi2021gender;@guimera2005team;@yang2022gender], to the domain of teaching. The significant gender patterns and underrepresentation of mixed-gender co-teaching teams echo the literature on homophily and bias in team formation within research collaborations [e.g., @kwiek2021gender] and underscore the critical role of gender dynamics in shaping not only scientific production but also pedagogical practices. Moreover, by combining analysis of a massive syllabi dataset with Monte Carlo simulations of gender-neutral team formation, our findings show that these patterns cannot be explained solely by country-level, institutional, and field-specific factors, such as cultural barriers or gender imbalance in specific fields. This evidence highlights the need to investigate these gender dynamics further, focusing on the underlying causal mechanisms that limit gender-diverse collaborations in teaching, a critical direction for future research.

Secondly, building on prior research that measures interdisciplinary curricula [@evans2016measuring] and examines their effects on student outcomes [@han2023interdisciplinary], our study shifts the focus to interdisciplinarity, linking it to the size and gender composition of teaching teams. While we find only minor and inconsistent gender differences in solo-taught teams, interdisciplinarity significantly increases in mixed-gender teaching teams. This pattern is associated with the presence of women collaborators, who tend to be more interdisciplinary when working in teams. These findings extend the literature that compares interdisciplinarity between men and women in academic research [@pinheiro2022women] to the teaching domain, establishing a novel connection between gender diversity and interdisciplinary teaching practices. This connection highlights a potential lever for universities and academic institutions seeking to foster interdisciplinarity in their curricula.

Thirdly, our study advances our understanding of gender disparities in academic recognition by extending the focus beyond scholarly citations to teaching materials. While prior research has predominantly focused on gender citation gaps in academic publications [e.g., @dion2018gendered], our study demonstrates the critical role of gender dynamics in the content presented in class and assigned readings. More specifically, our findings align with prior research on gendered citation patterns in the academic literature [e.g., @dion2018gendered], which shows that female scholars are more likely to cite work by other women. Interestingly, Dion et al. [@dion2018gendered] finds that mixed-gender research teams do not cite more women than male-only teams, highlighting a divergence from our course-level results. This finding indicates that instructor gender is associated with reading lists in ways that may differ from research citation patterns and that mixed-gender teaching teams could foster greater gender diversity in assigned readings. Together, these findings suggest new potential drivers of gender stereotypes in academia [@chatterjee2021gender], underscoring the need to broaden research on the causal mechanisms underlying gender disparities in citation practices to include teaching contexts, thereby moving beyond the current emphasis on scholarly citations alone. 

Finally, our findings reveal a persistent gender-based pattern in the assignment of novel materials, with female instructors tending to include more recent content in their syllabi than male instructors. In contrast, mixed-gender teams—or teams in general—tend to assign more conventional readings and cite scientific articles with lower atypicality. This evidence points to a complex relationship between team composition and teaching innovation that warrants further investigation. 

There are many possible explantions for these patterns. Female instructors may assign more recent readings because they enter the profession more recently, which could account for a weakening association between instructor gender and recency over time. Similarly, mixed-gender teams may rely on less atypical or more conventional readings because instructors from different fields must establish a shared foundation rooted in classic works. Taken together with our previous finding that interdisciplinary content is more common in mixed-gender teams, these results suggest that interdisciplinary courses may inherently require more conventional readings to bridge disciplinary differences. Nevertheless, our data do not allow to fully account for cohort effects or other potential confounders, as discuss below.

Overall, unveiling these associations contributes to understanding the observed gender-innovation gap in tertiary education [e.g., @biasi2022education]. However, while our results suggest a strong gender association, they remain inconclusive regarding its underlying drivers, whether the pattern reflects gender per se or is confounded by age or career stage (e.g., younger vs. female instructors). Notably, this trend coincides with the growing presence of women entering academia during the study period, suggesting that newer instructors may play a key role in pushing curricular boundaries. Nonetheless, further research is needed to disentangle the influence of gender from other intersecting factors, such as cohort effects, field-specific norms, and institutional context.

## Limitations

Our analysis bears several limitations. First, the dataset does not include granular information on the course's subfields that go beyond the 69 top-level fields identified in the dataset. If male and female instructors tend to concentrate on different subfields [e.g., @chari2017gender], the observed underrepresentation of mixed-gender teams may reflect limited availability of instructors of the other gender in the subfield, especially for advanced courses where teaching teams are more likely to form around narrower areas of expertise. This limitation prevents disentangling the exact driver of mixed-gender underrepresentation, which can derive from gender-based preferences towards subfields, limiting availability, or a tendency to seek same-gender partners or homophily. Further research is needed to fully disentangle these underlying mechanisms.

Second, our data lack detailed information on institutional assignment procedures and instructor characteristics, such as experience or academic rank. In most settings, teaching teams are not freely formed but are assigned by departments based on expertise and course needs. As a result, course characteristics, such as interdisciplinarity, may themeselves drive the composition of teaching teams. For example, courses that span multiple areas, may be more likely to require instructors from different fields, which given gender-sorting could increase the likelihoood of gender diverse teams. This introduces an important alternative explanation for our findings, whereby course content shapes team composition rather then the reverse  (inverse causality). While we partly account for instructors' experience using the order of appearance in the syllabus, our results should be interpreted as correlations, and we cannot entirely rule out that institutional allocation processes contribute to the observed patterns.

Third, our measurement of novelty in syllabi is constrained by the limited citation base typical of course materials and the temporal mismatch between publication-time novelty and the novelty students experience during instruction. These factors limit our capacity to apply systematically standard novelty metrics to teaching materials [e.g., @uzzi2013atypical]. Yet, by combining multiple measures, our work provides a viable path to characterise the multidimensional nature of innovation in teaching using syllabi data.

Fourth, institutional policies regarding teaching loads and the recognition of co-teaching vary substantially across countries and institutions. In many universities, team teaching does not fully count toward teaching loads or is treated as an overload, limiting faculty opportunities to engage in it even if they wish to. Moreover, teaching teams are not always determined by individual instructors’ preferences: in many institutions, course assignments and team composition are partially or entirely determined at the departmental or program level—for example, by course coordinators, curriculum structures, or administrative rules. In such cases, team formation may reflect institutional or organizational preferences rather than instructors’ choices. Our data do not capture these institutional constraints or assignment mechanisms, which may mechanically reduce or shape the observed incidence of mixed-gender teams. Consequently, our descriptive patterns reflect both individual preferences and the structural opportunities and assignment practices provided by institutions.

Finally, although our data covers 50% of educational institutions in the selected countries, and comparisons with official statistics on the distribution of academic staff and US graduates by field show a reasonable alignment with the trends observed in our sample, it is important to note that the sample is not fully representative of the underlying population. Additional research is needed to validate our results with appropriate weights or samples of the full population.

## Conclusion

Overall, this study offers critical insights into the academic market. As for research teams, teaching teams can impact instructors in multiple ways. First, junior faculty may have access to the experience and advice of senior faculty, which could increase their chances of promotion. Secondly, diverse teaching teams may inspire research collaborations, including interdisciplinary work. Finally, teaching assistants can actively seek out mentors and may benefit from these collaborations when applying for PhD programs or entering the labour market. Therefore, understanding how teaching teams are formed can help explain career trajectories.